services:
  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - '/app/node_modules'
      - './client:/app'
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development